# Generated by Django 3.2.6 on 2022-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdatafile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='masterdatafile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='masterdatafile',
            name='file_name',
            field=models.CharField(max_length=100, verbose_name='Uploaded By'),
        ),
    ]
