# Generated by Django 3.2.6 on 2022-11-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20221101_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdatafile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
